[package]
name = "axum-fundamentals"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
anyhow = "1.0.86"
httpc-test = "0.1.9"

[dependencies]
axum = "0.6"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }
tower-cookies = "0.9"
tower-http = { version = "0.4", features = ["fs"] }
